FROM node:lts-slim
RUN apt-get update ; apt-get install -y python make g++
WORKDIR /service
COPY *.js package* README* ./
COPY src src
COPY util util
RUN npm ci ; npm cache clean --force
RUN apt-get purge -y --auto-remove python make g++ ; apt-get clean
EXPOSE 5000
ENTRYPOINT [ "npm", "start" ]

