version: '3'

services:
  backend:
    image: backend:latest
    environment:
      - FRONT_URL=http://localhost:5000
    ports:
      - 8000:8000
  frontend:
    image: frontend:latest
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000
