version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  backend:
    image: backend:latest
    environment:
      - FRONT_URL=http://localhost:80
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=pass12345
      - DB_NAME=postgres
      - DB_HOST=postgres
  redis:
    image: redis:6
    volumes:
      - ./redis:/data
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=pass12345
    volumes:
      - ./database:/var/lib/postgresql/data
  frontend:
    image: frontend:latest
    environment:
      - API_URL=http://localhost:80
